data_law : /home/trduong/Data/counterfactual_fairness_game_theoric/data/raw/law_data.csv
data_adult : /home/trduong/Data/counterfactual_fairness_game_theoric/data/raw/adult.data
processed_data_adult : /home/trduong/Data/counterfactual_fairness_game_theoric/data/raw/processed_adult.csv

result_law : /home/trduong/Data/counterfactual_fairness_game_theoric/reports/results/law.csv
result_evaluate_law : /home/trduong/Data/counterfactual_fairness_game_theoric/reports/results/evaluate_law.csv
result_ivr_law : /home/trduong/Data/counterfactual_fairness_game_theoric/reports/results/law_ivr.csv

result_adult : /home/trduong/Data/counterfactual_fairness_game_theoric/reports/results/adult.csv
result_evaluate_adult : /home/trduong/Data/counterfactual_fairness_game_theoric/reports/results/evaluate_adult.csv

log_law : /home/trduong/Data/counterfactual_fairness_game_theoric/logs/law.log
log_train_law : /home/trduong/Data/counterfactual_fairness_game_theoric/logs/law_train.log
evaluate_law : /home/trduong/Data/counterfactual_fairness_game_theoric/logs/evaluate.log

ae_model_law : /data/trduong/counterfactual_fairness_game_theoric/models/ae_model_law.pt
state_dict_law : /data/trduong/counterfactual_fairness_game_theoric/models/state_dict_law.pth


